QuestGame/Areas/Admin/Controllers/StagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QuestGame.Models;

namespace QuestGame.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class StagesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Admin/Stages/Create
        public async Task<ActionResult> Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var game = await db.Games.FindAsync(id.Value);
            ViewBag.Games = new SelectList(db.Games, "ID", "Name",id.Value);
            ViewBag.Location = new SelectList(db.Locations, "ID", "Name");

            ViewBag.GameID = id.Value;
            return View(new Stage { Position = game.Stages.Count +1});
        }

        // POST: Admin/Stages/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "GameID,Question,Answer,QRQuestion,Help,LocationID,Position")] Stage stage)
        {
            if (ModelState.IsValid)
            {
                db.Stages.Add(stage);
                await db.SaveChangesAsync();
                return RedirectToAction("Details","Games", new { id = stage.GameID });
            }
            ViewBag.Games = new SelectList(db.Games, "ID", "Name", stage.GameID);
            ViewBag.Location = new SelectList(db.Locations, "ID", "Name",stage.LocationID);
            ViewBag.GameID = stage.GameID;
            return View(stage);
        }

        // GET: Admin/Stages/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stage stage = await db.Stages.FindAsync(id);
            if (stage == null)
            {
                return HttpNotFound();
            }
            ViewBag.Games = new SelectList(db.Games, "ID", "Name", stage.GameID);
            ViewBag.Location = new SelectList(db.Locations, "ID", "Name", stage.LocationID);

            return View(stage);
        }

        // POST: Admin/Stages/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,GameID,Question,Answer,QRQuestion,Help,LocationID,Position,DateSync")] Stage stage)
        {
            if (ModelState.IsValid)
            {
                db.Entry(stage).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Details", "Games", new { id = stage.GameID });
            }
            ViewBag.Games = new SelectList(db.Games, "ID", "Name", stage.GameID);
            ViewBag.Location = new SelectList(db.Locations, "ID", "Name", stage.LocationID);

            return View(stage);
        }

        // GET: Admin/Stages/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Stage stage = await db.Stages.FindAsync(id);
            if (stage == null)
            {
                return HttpNotFound();
            }
            return View(stage);
        }

        // POST: Admin/Stages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Stage stage = await db.Stages.FindAsync(id);
            db.Stages.Remove(stage);
            db.StagesDelete.Add(new StageDelete() { ID = stage.ID });
            await db.SaveChangesAsync();
            return RedirectToAction("Details", "Games", new { id = stage.GameID });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QuestGame/Areas/ApiSyncService/Controllers/StagesController.cs
using QuestGame.Areas.ApiSyncService.Models;
using QuestGame.Models;
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Http;

namespace QuestGame.Areas.ApiSyncService.Controllers
{
    [Authorize]
    public class StagesController : ApiController
    {

        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: 
        public IQueryable<Stage> GetStages()
        {
            return db.Stages;
        }

        /// GET: 
        public async Task<IHttpActionResult> GetStagesUpdated(DateTime DateSync)
        {
            if (DateSync == null)
            {
                return BadRequest();
            }
            var stages = db.Stages.AsNoTracking()
                                  .Where(s => s.DateSync > DateSync);
                                        
            var stagesDelete =  db.StagesDelete.AsNoTracking()
                                               .Where(s => s.DateDelete > DateSync);
                                       
            var StagesPack = new SyncPack<Stage, StageDelete>(await stages.ToListAsync(),
                                                              await stagesDelete.ToListAsync());
            return Ok(StagesPack);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

QuestGame/Areas/Admin/Views/Stages/Create.cshtml
@model QuestGame.Models.Stage

@{
    ViewBag.Title = "Добавление этапа в сценарий игры";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 class="page-header">Добавление этапа в сценарий игры</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Question, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Question,5,0, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Question, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QRQuestion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QRQuestion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QRQuestion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Answer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Answer,1,0, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Answer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Help, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Help, 3, 0, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Help, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocationID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.LocationID, ViewBag.Location as SelectList, "Выберите вариант", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocationID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GameID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.GameID, ViewBag.Games as SelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GameID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад к сценарию", "Details", new { Controller = "Games", id = ViewBag.GameID }, new {@class ="btn btn-default"})
</div>

QuestGame/Areas/Admin/Views/Stages/Delete.cshtml
@model QuestGame.Models.Stage

@{
    ViewBag.Title = "Удаление этапа";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 class="page-header">Удаление этапа</h2>

<h3 class="page-header">Вы действительно хотите удалить данный этап?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Game.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Game.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Question)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Question)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QRQuestion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QRQuestion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Answer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Answer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Help)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Help)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <dl class="dl-horizontal">
                <dt>
                    
                </dt>
                <dd>
                    <input type="submit" value="Удалить" class="btn btn-primary" />
                </dd>
            </dl>
        </div>
        <div>
            @Html.ActionLink("Назад к сценарию", "Details", new { Controller = "Games", id = Model.GameID }, new { @class = "btn btn-default" })
        </div>
    }
</div>

QuestGame/Areas/Admin/Views/Stages/Edit.cshtml
@model QuestGame.Models.Stage

@{
    ViewBag.Title = "Редактирование этапа";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 class="page-header">Редактирование этапа</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Question, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Question, 5, 0, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Question, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QRQuestion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QRQuestion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QRQuestion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Answer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Answer, 1, 0, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Answer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Help, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Help, 3, 0, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Help, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocationID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.LocationID, ViewBag.Location as SelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocationID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GameID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.GameID, ViewBag.Games as SelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GameID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
                @*@Html.ActionLink("Удалить", "Delete", "Stages", new { id = Model.ID }, new { @class = "btn btn-primary" })*@
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад к сценарию", "Details", new { Controller = "Games", id = Model.GameID }, new {@class = "btn btn-default" })
</div>